### PR TITLE
Allow for NC 24

### PR DESCRIPTION
**Pull request by PVince81**
- [x] quick smoke test: registration worked

### CODE REVIEW

**Comment by nickvergessen** [comment]
Yes it works (apart from wrongly configured unit test).
However this app is released from the master branch and therefore can only have 24 set as a limit once it is okay to put into the appstore, aka. feature-freeze time or RC1 time

**Comment by PVince81** [comment]
we will need to unblock 24 at least for https://github.com/nextcloud/registration/issues/391, or we can do so as part of that task

**Comment by PVince81** [comment]
hmmm... and switching to the new button component would make the app incompatible with NC < 24 so we'll need to start using stable branches then

**Comment by nickvergessen** [comment]
We have a stable branch for 19 and older already.
Question is why would it not be backword compatible. Is it depending on server css again? Or is legacy having interfering css?

**Comment by skjnldsv** [comment]
Yes, we do that already in many apps.
Unless we want to bind with server apis, it should not be needed to move to a stablex repository structure

**Review by skjnldsv — APPROVED** [review]

**Review by nickvergessen — CHANGES_REQUESTED** [review]
Needs CI and stuff to execute as well.
Will take over

**Pull request merged**
