### PR TITLE
Use the primary color and adjust the width when it's the only option

### LINKED ISSUE #68: app not fully compliant with theming
I would expect the 'register' button to be the same color as Nextcloud's 'login' button, but that's currently not the case.

### PR DESCRIPTION
**Pull request by nickvergessen**
Before | After
---|---
Bildschirmfoto von 2020-07-10 14-15-12 | Bildschirmfoto von 2020-07-10 14-14-52

Fix #68 

cc @Becker-Asano

### CODE REVIEW

**Comment by zorn-v** [comment]
I think change "global" styles in app is not good idea. 
Your button will be looks different (and may be buggy) on others version of nextcloud.

**Comment by nickvergessen** [comment]
What exactly do you mean?

**Comment by zorn-v** [comment]
You set fixed width for registration button with fixed margin also. 
What happen if width of container will modified in next nextcloud versions styles ?
What if will be decided to change login button width etc.

In previous NC versions (prior to 18 AFAIR), container width was 300px AFAIR

**Comment by nickvergessen** [comment]
This change is only available for the next version which will be only available on nextcloud 20 and later. If that button changes again we will adapt again.

**Comment by zorn-v** [comment]
Taking into account how "fast" issue like this https://github.com/nextcloud/registration/issues/210 is resolving, I doubt that it will be fast. 
And users may endure ugly button through several NC versions )

**Pull request merged**
