### PR TITLE
Terms of service integration

### LINKED ISSUE #287: Integrate with 📜 Terms of service
When the [:scroll: Terms of service](https://github.com/nextcloud/terms_of_service) app is enabled and configured it should show up on the registration form and checking it there should store it for the user

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #287

### CODE REVIEW

**Comment by nickvergessen** [comment]
ToS PR is at https://github.com/nextcloud/terms_of_service/pull/511

**Review by PVince81 — APPROVED** [review]
code looks fine :+1:

**Comment by PVince81** [comment]
seems the linter wants some changes though

**Review by danxuliu — APPROVED** [review]
Tested and works :+1:

**Comment by hobbsecky** [comment]
Nice one. Working as expected!

**Pull request merged**
