### PR TITLE
Make email optional

### PR DESCRIPTION
**Pull request by skaramicke**
In the Operation Tulip implementation of Nextcloud, absolute user integrity is key. Therefore we require a way for users to register without supplying any identifiable information. Although they could absolutely go register an anonymous email account somewhere, or just make up a fake email address if verification is turned off, we see the need to make this both intuitive and easy to use for the users.

It would greatly help us maintain our implementation if this optional email field could be part of the main repository of the registration app.

Respectfully yours,
Mikael Grön
Coder at Operation Tulip

### CODE REVIEW

**Comment by nickvergessen** [comment]
Sounds sane, I will have a look next week 👍

**Comment by TheOneWithTheBraid** [comment]
Fixes #273

**Comment by TheOneWithTheBraid** [comment]
My first impression of the implementation is quite good. Please merge this soonly! We are currently workarrounding by client side JS which is highly unreliable. I am glad to see someone got the time to write a proper implementation.

**Comment by TheOneWithTheBraid** [comment]
Is there any official opinion on this PR? I am definitely waiting for this to be merged.

**Comment by nickvergessen** [comment]
I'm lacking time atm, but when it works we will take it once I had time to review it.

**Comment by skaramicke** [comment]
> I'm lacking time atm, but when it works we will take it once I had time to review it.

You mean it is not working? If there’s a problem, I’m not aware of it. 

Please mention me if anything needs fixing in the code.

**Comment by TheOneWithTheBraid** [comment]
@nickvergessen In our large-scale setup, it's working perfectly. I really can't wait for it to be merged - it's such an important feature.

**Comment by nickvergessen** [comment]
Merged via #364 and will come with the release that also brings compatibility for 23

**Pull request closed without merging**
