### PR TITLE
Include settings section

### PR DESCRIPTION
**Pull request by jotoeri**
I was wondering why the registration settings are a bit apart, hidden in the additional settings. Probably due to historical reasons, when it was just a few settings?
I think with this list of settings it is (meanwhile?) appropriate to create a separate section for the registration app, where it is just more within view.

Also i changed the icon now to use servers group-icon, which is used for users-settings, too. Basically, the registration belongs to users-settings imo. I just copied the svg from server, however i'm not sure, if this is ok with the license and stuff. Probably @nickvergessen can tell me?

Feedback & opposing opinions are welcome! 😉 

Greets,
Jonas

EDIT: Just recognized with the current svg, the logo is white in the App-List, but black in Settings. If i set a black fill-color this just turns around. Any idea how to solve this? 😄 

Before:
grafik

After:
grafik

### CODE REVIEW

**Comment by nickvergessen** [comment]
Sounds like a good idea.

I replaced the app icon with `AccountPlus` of material design. I think it fits a bit better.

**Comment by nickvergessen** [comment]
okay github is broken now. It's clearly on the branch, but not in the PR view....

**Review by nickvergessen — APPROVED** [review]

**Comment by jotoeri** [comment]
> I think it fits a bit better.

Definitely, yes 👍
I just removed my icon-commit from the branch...

**Comment by Daksol** [comment]
Sounds good. This brings **nextcloud/registration** in line with most other Apps, and improves the usability.
So one less special case to remember to document when bringing someone up to speed as an Admin.
Thanks.

**Comment by nickvergessen** [comment]
I will have a look with the white icon. I ise dark mode and there it looked good

**Comment by nickvergessen** [comment]
Icon color "fixed" now.
Dark mode app list is broken, but it seems to be a general issue

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
Thanks @jotoeri for the patch!

**Comment by jotoeri** [comment]
Thanks for fixing the rest, @nickvergessen 😉

**Comment by nickvergessen** [comment]
Dark mode app list fix is https://github.com/nextcloud/server/pull/25655

**Pull request merged**
