### PR TITLE
Use the account icon instead of the key icon for the uid field when display name isn't requested

### PR DESCRIPTION
**Pull request by tcitworld**
The « key » icon for the user id field creates confusion. Since the account icon is already used for the display name, we'll use it only if that's not already being used.

For reference, the previous behavior:
register

Of course if @nextcloud/designers has a better icon for this field, I'm really opened to an alternative.

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by jancborchardt — CHANGES_REQUESTED** [review]
@tcitworld on the log in screen we don’t use icons in the fields anymore, so it would be simplest if we remove them here too. :) Also, the first line "Bienvenue …" can be changed to a simple h2 saying "Create account", like on the log in page.

**Comment by nickvergessen** [comment]
> on the log in screen we don’t use icons in the fields anymore, so it would be simplest if we remove them here too

The login screen never had icon and only has 2 fields.

This screen can have up to 5 input fields, so I think it can be helpful for people to have an icon as visual help what the field is about.

**Comment by tcitworld** [comment]
Yeah, I think it makes sense to keep the icon too. We can add a simple title on the top in an extra PR.

For reference, the user popup in users management doesn't have icons, but placeholders. However it's much clearer for an admin what the difference between display names and usernames is (and this popup has other issues).

image

**Review by jancborchardt — APPROVED** [review]
> The login screen never had icon and only has 2 fields.

@nickvergessen It totally did :) (granted, in ownCloud times) https://duckduckgo.com/?q=owncloud+login+screen&t=newext&atb=v339-1&iax=images&ia=images

> This screen can have up to 5 input fields, so I think it can be helpful for people to have an icon as visual help what the field is about.

Ok, makes sense, I’m fine with keeping them as well. And this change fixes the issue I would have had with the icons. :)

**Pull request merged**
